project:
  type: website
  output-dir: "../docs/en"

website:
  back-to-top-navigation: true
  navbar:
    pinned: false
    logo: images/logo_final_orange_darkbg_v2.png
    left:
      - text: Home
        href: index.qmd
      - text: "The survey"
        menu:
          - text: Overview
            href: Survey.qmd
          - text: Recruitment
            href: Recruitment.qmd
          - text: Registry
            href: https://osf.io/mtrnf/overview
          - text: Survey protocol
            href: Protocol.qmd
      - text: Material and Information
        href: Materials.qmd
      - text: "Team"
        href: Principal.qmd
      - text: News
        href: news.qmd
    right:
      - text: "🌍 Language"
        menu:
          - text: "Deutsch"
            href: ../de/index.html
          - text: "Français"
            href: ../fr/index.html
      - icon: envelope
        text: Email
        href: mailto:David.Jackson-Perry@chuv.ch
      - icon: github
        href: https://github.com/alainamstutz/adhd-hiv-prep
  page-footer: © 2026  &middot; Made with [![](https://www.r-project.org/logo/Rlogo.png){fig-alt="R" width=25px}](https://www.r-project.org) and
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
  search:
    location: navbar
    type: textbox
    
format:
  html:
    theme: [quartz, styles.css]
    mainfont: "Arial, sans-serif"
    fontsize: 1.6rem

editor: visual

