project:
  type: website
  output-dir: "../docs/de"

website:
  back-to-top-navigation: true
  navbar:
    pinned: false
    logo: images/logo_final_orange_darkbg_v2.png
    left:
      - text: "Die Studie"
        menu:
          - text: Übersicht
            href: Survey.qmd
          - text: Rekrutierung
            href: Recruitment.qmd
          - text: Registry
            href: https://osf.io/mtrnf/overview
          - text: Studienprotokoll
            href: Protocol.qmd
      - text: Material und Informationen
        href: Materials.qmd
      - text: "Team"
        href: Principal.qmd
      - text: News
        href: news.qmd
    right:
      - text: "🌍 Sprache"
        menu:
          - text: "English"
            href: ../en/index.html
          - text: "Français"
            href: ../fr/index.html
      - icon: envelope
        text: Email
        href: mailto:David.Jackson-Perry@chuv.ch
      - icon: github
        href: https://github.com/alainamstutz/adhd-hiv-prep
  page-footer: © 2026  &middot; Made with [![](https://www.r-project.org/logo/Rlogo.png){fig-alt="R" width=25px}](https://www.r-project.org) and
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
  search:
    location: navbar
    type: textbox
    
format:
  html:
    theme: [quartz, styles.css]
    mainfont: "Arial, sans-serif"
    fontsize: 1.05rem

editor: visual

