project:
  type: website
  output-dir: "../docs/fr"

website:
  back-to-top-navigation: true
  navbar:
    pinned: false
    logo: images/logo_final_orange_darkbg_v2.png
    left:
      - text: Accueil
        href: index.qmd
      - text: "L'étude"
        menu:
          - text: Aperçu
            href: Survey.qmd
          - text: Recrutement
            href: Recruitment.qmd
          - text: Registre
            href: https://osf.io/mtrnf/overview
          - text: Protocole de l'étude
            href: Protocol.qmd
      - text: Matériel et informations
        href: Materials.qmd
      - text: "Équipe"
        href: Principal.qmd
      - text: Actualités
        href: news.qmd
    right:
      - text: "🌍 Langue"
        menu:
          - text: "English"
            href: ../en/index.html
          - text: "Deutsch"
            href: ../de/index.html
      - icon: envelope
        text: Email
        href: mailto:David.Jackson-Perry@chuv.ch
      - icon: github
        href: https://github.com/alainamstutz/adhd-hiv-prep
  page-footer: © 2026  &middot; Made with [![](https://www.r-project.org/logo/Rlogo.png){fig-alt="R" width=25px}](https://www.r-project.org) and
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
  search:
    location: navbar
    type: textbox
    
format:
  html:
    theme: [quartz, styles.css]
    mainfont: "Arial, sans-serif"
    fontsize: 1.6rem

editor: visual

