---
title: "Actualités"
format: html
---

*Traduction française à venir.*

<div class="news-wrapper">
<div class="news-item blue3">
  <h2>December 2025</h2>
  <p>**New publication**</p>
  <p>A commentary introducing the rationale for this study.</p>
  <p>*Jackson-Perry D, Amstutz A. Should we be paying more attention to HIV and adult ADHD? Lancet HIV. 2025 Dec;12(12):e813–4. doi:10.1016/S2352-3018(25)00235-8*</p>
</div>

<div class="news-item red2">
  <h2>15.07.2026</h2>
  <p>The website goes online.</p>
</div>
</div>

<style>
.news-wrapper {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.news-item {
  border: 1px solid #ccc;
  padding: 20px;
  color: black;
  border-radius: 15px;
  transition: all 0.3s ease;
}

.news-item.red1 { background-color: #E6B0AA; }
.news-item.red2 { background-color: #F5B7B1; }
.news-item.blue1 { background-color: #D7BDE2; }
.news-item.blue2 { background-color: #D2B4DE; }
.news-item.blue3 { background-color: #A9CCE3; }
.news-item.blue4 { background-color: #AED6F1; }
.news-item.green1 { background-color: #A3E4D7; }
.news-item.green2 { background-color: #A2D9CE; }
.news-item.green3 { background-color: #A9DFBF; }
.news-item.green4 { background-color: #ABEBC6; }
.news-item.yellow1 { background-color: #F9E79F; }
.news-item.yellow2 { background-color: #FAD7A0; }
.news-item.yellow3 { background-color: #F5CBA7; }
.news-item.yellow4 { background-color: #EDBB99; }

.news-item img {
  max-width: 100%;
  height: auto;
  margin-bottom: 15px;
}
.news-item h2 {
  margin-top: 0;
}

.news-wrapper:hover .news-item {
  opacity: 0.4;
  filter: grayscale(100%);
}
.news-item:hover {
  opacity: 1 !important;
  filter: none !important;
  transform: scale(1.02);
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  z-index: 2;
  position: relative;
}
</style>
